stages:
 - docker
 - check
 - test
 - checkWindows
 - release

variables:
  VERSION: "0.1.6.1"
  PKG: "rENA"
  PKGL: "rena"
  REG_URL: "${CI_REGISTRY}/epistemic-analytics/qe-packages/rena"
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

# Templates
.build_definition: &build_template
  before_script:
    - export _R_CHECK_CRAN_INCOMING_=FALSE
    - export _R_CHECK_FORCE_SUGGESTS_=TRUE
    - mkdir -p archive/
    - rm -f ./R/RcppExports.R
    - mkdir -p ~/.R/
    - rm -f ~/.R/Makevars
    - cp demo/backup/Makevars ~/.R/
    - Rscript -e 'Rcpp::compileAttributes()'
    - Rscript -e 'update(devtools::dev_package_deps("."))'
    - cd ..; R CMD build --log rENA || true
.check_definition: &check_template
  stage: check
  artifacts:
    paths:
      - build/
      - archive/
      - doc/
      - inst/doc/
    expire_in: 1 week
  <<: *build_template
  script:
    # - R -e "devtools::test('./rENA')"
    - R --no-site-file --no-environ --no-save --no-restore --quiet CMD check rENA_$VERSION.tar.gz --as-cran --no-manual
    - mv ./rENA-00build.log rENA/archive/ || true
    - mv ./rENA.Rcheck/00check.log rENA/archive/ || true
    - mv ./rENA.Rcheck/00install.out rENA/archive/ || true
    - mv ./rENA_*.tar.gz rENA/archive/ || true
  tags:
    - docker
  allow_failure: false

# Check Steps
check:r-devel:
  image: $REG_URL/devel:current
  only:
    - master
  <<: *check_template
check:r-oldrelease:
  image: $REG_URL/old-release:current
  only:
    - master
  <<: *check_template
check:r-release:
  image: $REG_URL/release:current
  only:
    - master
  <<: *check_template
check:r-winbuilder:
  stage: checkWindows
  image: egruw/r-ftp
  when: manual
  script:
    - curl -v -T archive/${PKG}_${VERSION}.tar.gz ftp://win-builder.r-project.org/R-oldrelease/${PKG}_${VERSION}.tar.gz
    - curl -v -T archive/${PKG}_${VERSION}.tar.gz ftp://win-builder.r-project.org/R-release/${PKG}_${VERSION}.tar.gz
    - curl -v -T archive/${PKG}_${VERSION}.tar.gz ftp://win-builder.r-project.org/R-devel/${PKG}_${VERSION}.tar.gz
  tags:
    - docker
  allow_failure: false

test:r-release:
  stage: test
  image: $REG_URL/release:current
  variables: 
    FILE: "inst/coverage/covr.json"
    S3BUCKET: "qe-package-coverage"
    S3STORAGETYPE: "STANDARD"
    AWSREGION: "s3-us-west-2"
    CONTENTTYPE: "text/json"
    RESOURCE: "qe-package-coverage/inst/coverage/covr.json"
    DATEVALUE: "Mon, 12 Aug 2019 11:41:13 GMT"
    STRINGTOSIGN: "PUT\r\n\r\ntext/json\r\nMon, 12 Aug 2019 11:41:13 GMT\r\nqe-package-coverage/inst/coverage/covr.json"
    #SIGNATURE=`echo -en ${STRINGTOSIGN} | openssl sha1 -hmac ${AWS_S3_SECRET} -binary | base64`
  before_script:
    - Rscript -e 'install.packages(c("covr"), repos="http://cran.rstudio.com")'
    - Rscript -e 'install.packages(c("aws.s3","aws.signature"), repos="http://cran.rstudio.com")'
  script:
    #- 'echo ${STRINGTOSIGN}'
    #- 'echo ${AWS_S3_SECRET}'
    #- 'echo -en ${STRINGTOSIGN} | openssl sha1 -hmac ${AWS_S3_SECRET} -binary | base64'
    #- 'curl -X PUT -T "${FILE}" -H "Host: ${S3BUCKET}.s3.amazonaws.com"  -H "Date: ${DATEVALUE}" -H "Content-Type: ${CONTENTTYPE}" -H "Authorization: AWS ${AWS_S3_KEY}:`echo -en ${STRINGTOSIGN} | openssl sha1 -hmac ${AWS_S3_SECRET} -binary | base64`" https://${S3BUCKET}.s3.amazonaws.com/${FILE}'
    - 'Rscript -e "aws.s3::put_object(bucket = \"${S3BUCKET}\", file = \"${FILE}\")"'
    #- Rscript -e "covr::coveralls()"
    #- cov <- covr::package_coverage( type = "tests" )
    #- rep <- covr::report(cov, file = "inst/coverage/rENA.html")
  artifacts:
    paths:
      - inst/coverage/
    expire_in: 10 years
  dependencies:
    - check:r-release

release:cran:
  stage: release
  image: egruw/r-ftp
  dependencies:
    - check:r-release
  only:
    - tags
  except:
    - branches
  when: manual
  script:
    - cat cran-comments.md
    - Rscript -e "devtools:::upload_cran(devtools::as.package('.'), './archive/rENA_$VERSION.tar.gz')"
  tags:
    - docker
  allow_failure: false


.docker_definition: &docker_template
  stage: docker
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $REG_URL/$TAG:current -f inst/docker/${PKG}-$FILE inst/docker/
    - docker push $REG_URL/$TAG:current
  only:
    refs:
      - develop
    changes:
      - "inst/docker/rENA-$FILE"
      - ".gitlab-ci.yml"
docker:release:
  variables:
    TAG: "release"
    FILE: "release"
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  <<: *docker_template
docker:old-release:
  variables:
    TAG: "old-release"
    FILE: "oldrelease"
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  <<: *docker_template
docker:devel:
  variables:
    TAG: "devel"
    FILE: "devel"
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  <<: *docker_template
