stages:
  - setup
  - docker
  - build
  - check
  - package
  - release

variables:
  VERSION: "0.2.3"
  PKG: "rENA"
  PKGL: "rena"
  REG_URL: "${CI_REGISTRY}/epistemic-analytics/qe-packages/${PKGL}"

include:
  - project: 'epistemic-analytics/qe-packages/cranqe'
    ref: master
    file:
      - '/public/ci_templates/setup_template.yml'
      - '/public/ci_templates/rhub_template.yml'
      - '/public/ci_templates/build_template.yml'
      - '/public/ci_templates/cranqe_release_template.yml'
