---
title: "hena-example"
author: "Cody L Marquart"
date: '2022-07-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## hENA Example



```{r}
codeNames = c("Data","Technical.Constraints","Performance.Parameters","Client.and.Consultant.Requests","Design.Reasoning","Collaboration")
accum = ena.accumulate.data(
  units = RS.data[,c("Condition","UserName","GameHalf")],
  conversation = RS.data[,c("Condition","GroupName","GameHalf")],
  metadata = RS.data[,c("CONFIDENCE.Change","CONFIDENCE.Pre","CONFIDENCE.Post","C.Change")],
  codes = RS.data[,codeNames],
  model = "EndPoint",
  window.size.back = 4
);
set = ena.make.set(enadata = accum);

value_variables = colnames(set$model$points.for.projection)[9:23]
#
# # Test 1 begin
x_variable = "Condition"
# test_set11 = ena.rotation.h(enaset = set, list(x_var = x_variable) )

set_11 = ena.make.set(
  enadata = accum,
  rotation.by = ena.rotation.h,
  rotation.params = list(x_var = x_variable)
)
```

```{r}
# # test_set12 = ena.rotation.h(enaset = set,value_vars = value_variables, x_var = x_variable, formula = "GameHalf")
# # # Test 1 end
# #
# # # # Test 2 begin
# y_variable = "GameHalf"
# test_set22 = ena.rotation.h(enaset = set, list(x_var = x_variable, y_var = y_variable) )
# set_22 = ena.make.set(
#   enadata = accum,
#   rotation.by = ena.rotation.h,
#   rotation.params = list(x_var = x_variable, y_var = y_variable)
# )
# # # # Test 2 end
#
# # #
# # # # Test 3 begin
# # # test_set3=ena.rotation.h(enaset = set,value_vars = value_variables,x_var=x_variable,y_var = y_variable,include_xy = TRUE)
# # # # Test 3 ends
# # #
# # # # Test 4 begin
# # controls = c("GameHalf")
# # # test_set41 = ena.rotation.h(enaset = set,value_vars = value_variables,x_var=x_variable, control_vars = controls)
# # # test_set4=ena.rotation.h(enaset = set, value_vars = value_variables, x_var = x_variable, y_var = y_variable, control_vars = controls)
# # # ena.rotation.h(enaset = set, value_vars = value_variables, x_var = x_variable)
# # # # Test 4 ends
# # #
# # # ### Test block end

```
