---
title: ENA Methods
output: rENA::methods_report
---
`r ub = enaset$enadata$function.params$units.by`
`r u = enaset$enadata$units`
`r wb = enaset$enadata$function.params$window.size.back`
`r wgt = enaset$enadata$function.params$weight.by`
In this study, we applied Epistemic Network Analysis (Shaffer, 2017; Shaffer, Collier, & Ruis, 2016; Shaffer & Ruis, 2017) to our data. 

We defined the units of analysis as all lines of data associated with a single value of `r ub[1]``r if(length(ub) > 1) paste0(" subsetted by ", concatenate::cc_and(ub[2:length(ub)], oxford=T))`. For example, one unit consisted of all the lines associated with `r concatenate::cc_and(apply(matrix(c(ub, as.matrix(u[1,])[1,]), nrow=2), 1, paste, collapse=" "), oxford=T)`.

`r if(identical(wb, "Conversation")) "The ENA algorithm constructs a network model for each unit of analysis, showing how the codes in all lines associated with that unit—within a given set of lines called a conversation—are connected to one another. The resulting networks are aggregated for all conversations for each unit of analysis in the model."``r if(is.numeric(wb)) "The ENA algorithm uses a moving window to construct a network model for each line in the data, showing how codes in the current line are connected to codes that occur within the recent temporal context (Siebert-Evenstone et al., 2017), defined as "``r if(!is.infinite(wb)) paste0(wb," lines (each line plus the ",(wb-1)," previous lines)")else"all lines preceding the current line"` within a given conversation. The resulting networks are aggregated for all lines for each unit of analysis in the model. In this model, we aggregated networks using a `r if(identical('binary',wgt))"binary"else"weighted"` summation in which the networks for a given`r if(identical(wb, "Conversation")) " conversation"else" line"`} reflect`r if(identical('binary',wgt)){" the presence or absence of the co-occurrence"}else if(identical(wgt, 'product')){" the product of the value"}else if(identical(wgt,'sqrt')){" square root of the product"}else{" log of the product"}` of each pair of codes.



References

Arastoopour, G., Swiecki, Z., Chesler, N. C., & Shaffer, D. W. (2015). Epistemic Network Analysis as a tool for engineering design assessment. Presented at the American Society for Engineering Education, Seattle, WA.

Shaffer, D. W. (2017). Quantitative ethnography. Madison, WI: Cathcart Press.

Shaffer, D. W., Collier, W., & Ruis, A. R. (2016). A tutorial on epistemic network analysis: Analyzing the structure of connections in cognitive, social, and interaction data. Journal of Learning Analytics, 3(3), 9–45.

Shaffer, D. W., & Ruis, A. R. (2017). Epistemic network analysis: A worked example of theory-based learning analytics. In C. Lang, G. Siemens, A. F. Wise, & D. Gasevic (Eds.), Handbook of learning analytics (pp. 175–187). Society for Learning Analytics Research.

Siebert-Evenstone, A., Arastoopour Irgens, G., Collier, W., Swiecki, Z., Ruis, A. R., & Williamson Shaffer, D. (2017). In Search of Conversational Grain Size: Modelling Semantic Structure Using Moving Stanza Windows. Journal of Learning Analytics, 4(3), 123–139. https://doi.org/10.18608/jla.2017.43.7

Sullivan, S. A., Warner-Hillard, C., Eagan, B. R., Thompson, R., Ruis, A. R., Haines, K., … Jung, H. S. (2017). Using epistemic network analysis to identify targets for educational interventions in trauma team communication. Surgery, in press.
