name = "ENA"
uuid = "c6c8b45b-0626-44bf-962f-99430808f29b"
authors = ["Cody L Marquart <cody.marquart@wisc.edu>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
CxxWrap = "0.15"
julia = "1.9"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "Random"]
