"""Tests for ena.libena rotations (moved from qe-lib's qe.rotation).

The Python tests verify qe against numpy references that replicate
rENA's canonical math directly. (The R test suite verifies the same math
against rENA fixtures generated by `rENA:::orthogonal_svd` and prcomp —
both targets should produce identical reference values for the same input.)

Sign convention: rENA inherits LAPACK's SVD signs. Both numpy.linalg.svd
and Armadillo go through the same Accelerate/OpenBLAS LAPACK on macOS, so
in practice the signs match — but the tests compare up to per-column sign
flips to remain robust across BLAS implementations.
"""
import numpy as np
import pytest
# Moved from qe-lib's tests with libena (libqe's phase 4a split). The old
# module names are aliased to ena.libena so the test bodies are unchanged.
from ena import libena as rotation
from ena.libena import RotationResult


# ── helpers ──────────────────────────────────────────────────────────────────

def assert_columns_equal_up_to_sign(actual, expected, atol=1e-9):
    """Compare matrices column-by-column, allowing per-column sign flips."""
    assert actual.shape == expected.shape
    for j in range(expected.shape[1]):
        a, e = actual[:, j], expected[:, j]
        delta_pos = np.max(np.abs(a - e))
        delta_neg = np.max(np.abs(a + e))
        delta = min(delta_pos, delta_neg)
        assert delta <= atol, (
            f"column {j} differs from expected beyond sign flip "
            f"(min |Δ| = {delta:g} > {atol:g})"
        )


def reference_ena_svd(points):
    """Numpy reference matching prcomp(retx=F, scale=F, center=F, tol=0).
    Returns (rotation, eigenvalues) as a tuple.
    """
    _, s, VT = np.linalg.svd(points, full_matrices=True)
    V = VT.T
    n, p = points.shape
    denom = max(1, n - 1)
    eigenvalues = np.zeros(p)
    eigenvalues[: s.size] = (s ** 2) / denom
    return V, eigenvalues


def reference_means_rotation(points, group_pairs):
    """Numpy reference matching ena.rotate.by.mean — sequential deflation
    by normalized mean-diff axes, then rENA's orthogonal_svd."""
    centered = points - points.mean(axis=0)
    deflated = centered.copy()
    weights = np.zeros((centered.shape[1], len(group_pairs)))
    for i, (a, b) in enumerate(group_pairs):
        ma = deflated[list(a)].mean(axis=0)
        mb = deflated[list(b)].mean(axis=0)
        d = ma - mb
        axis = d / np.linalg.norm(d)
        deflated = deflated - np.outer(deflated @ axis, axis)
        weights[:, i] = axis

    # orthogonal_svd: QR(weights) → project deflated onto orth. complement →
    # SVD → recombine.
    p = weights.shape[0]
    k = weights.shape[1]
    Q, _ = np.linalg.qr(weights, mode="complete")
    Q_named = Q[:, :k]
    Q_comp = Q[:, k:]
    X_bar = deflated @ Q_comp
    V_inner, _ = reference_ena_svd(X_bar)
    rotation_mat = np.empty((p, p))
    rotation_mat[:, :k] = Q_named
    rotation_mat[:, k:] = Q_comp @ V_inner
    return rotation_mat


def reference_complete_rotation(points, named_axes):
    """Numpy reference for canonical ena.rotate.by.generalized tail —
    parallel deflation: defA = points - points @ named_axes @ named_axes.T."""
    p = named_axes.shape[0]
    k = named_axes.shape[1]
    defA = points - points @ named_axes @ named_axes.T
    V_inner, _ = reference_ena_svd(defA)
    rotation_mat = np.empty((p, p))
    rotation_mat[:, :k] = named_axes
    rotation_mat[:, k:] = V_inner[:, : (p - k)]
    return rotation_mat


def make_named_axes(points, group_pairs):
    """Build unit-norm mean-diff axes from centered group means — convenient
    inputs for testing complete_rotation."""
    centered = points - points.mean(axis=0)
    out = np.zeros((centered.shape[1], len(group_pairs)))
    for i, (a, b) in enumerate(group_pairs):
        d = centered[list(a)].mean(axis=0) - centered[list(b)].mean(axis=0)
        out[:, i] = d / np.linalg.norm(d)
    return out


# ── ena_svd ──────────────────────────────────────────────────────────────────

class TestEnaSvd:
    def test_matches_numpy_svd_up_to_sign(self):
        rng = np.random.default_rng(1)
        pts = rng.standard_normal((30, 4))
        pts_c = pts - pts.mean(axis=0)
        out = rotation.ena_svd(pts_c)
        ref_rot, ref_eig = reference_ena_svd(pts_c)
        assert_columns_equal_up_to_sign(out.rotation, ref_rot)
        np.testing.assert_allclose(out.eigenvalues, ref_eig, atol=1e-10)

    def test_eigenvalues_equal_sdev_squared(self):
        rng = np.random.default_rng(2)
        pts = rng.standard_normal((50, 6))
        pts_c = pts - pts.mean(axis=0)
        out = rotation.ena_svd(pts_c)
        _, s, _ = np.linalg.svd(pts_c, full_matrices=False)
        sdev = s / np.sqrt(max(1, pts_c.shape[0] - 1))
        np.testing.assert_allclose(out.eigenvalues[: s.size], sdev ** 2, atol=1e-10)

    def test_no_throw_for_exact_0025(self):
        """Regression: Jacobi skip used `<` so `0 < 0` didn't skip; theta=0/0=NaN."""
        pts = np.array([[0.296, 0.025, -0.274],
                        [-0.296, -0.025,  0.274]])
        out = rotation.ena_svd(pts)   # must not raise
        ev = np.sort(out.eigenvalues)[::-1]
        assert ev[0] > 0.1
        np.testing.assert_allclose(ev[1:], 0.0, atol=1e-10)

    def test_column_names(self):
        rng = np.random.default_rng(3)
        out = rotation.ena_svd(rng.standard_normal((10, 5)))
        assert out.column_names == ["SVD1", "SVD2", "SVD3", "SVD4", "SVD5"]

    def test_rotation_is_orthonormal(self):
        rng = np.random.default_rng(4)
        out = rotation.ena_svd(rng.standard_normal((50, 6)))
        np.testing.assert_allclose(
            out.rotation.T @ out.rotation, np.eye(6), atol=1e-10
        )


# ── deflate ──────────────────────────────────────────────────────────────────

class TestDeflate:
    def test_matches_manual_formula(self):
        rng = np.random.default_rng(7)
        d = rng.standard_normal((20, 4))
        axis = rng.standard_normal(4)
        axis /= np.linalg.norm(axis)
        expected = d - np.outer(d @ axis, axis)
        np.testing.assert_allclose(rotation.deflate(d, axis), expected, atol=1e-12)

    def test_result_orthogonal_to_axis(self):
        rng = np.random.default_rng(8)
        d = rng.standard_normal((15, 5))
        axis = rng.standard_normal(5)
        axis /= np.linalg.norm(axis)
        out = rotation.deflate(d, axis)
        assert np.allclose(out @ axis, 0.0, atol=1e-10)


# ── means_rotation ───────────────────────────────────────────────────────────

class TestMeansRotation:
    def test_one_pair_matches_reference(self):
        rng = np.random.default_rng(11)
        pts = rng.standard_normal((30, 4))
        pts[:15] += np.array([2.0, -1.0, 0.5, 0.0])
        pairs = [(list(range(15)), list(range(15, 30)))]
        out = rotation.means_rotation(pts, pairs)
        ref = reference_means_rotation(pts, pairs)
        assert_columns_equal_up_to_sign(out.rotation, ref)

    def test_two_pairs_matches_reference(self):
        rng = np.random.default_rng(12)
        pts = rng.standard_normal((50, 6))
        pts[:25, 0] += 1.5
        pts[:25, 2] -= 0.8
        pairs = [
            (list(range(25)), list(range(25, 50))),
            (list(range(0, 10)) + list(range(25, 35)),
             list(range(10, 25)) + list(range(35, 50))),
        ]
        out = rotation.means_rotation(pts, pairs)
        ref = reference_means_rotation(pts, pairs)
        assert_columns_equal_up_to_sign(out.rotation, ref)

    def test_column_names_mr_then_svd(self):
        rng = np.random.default_rng(13)
        pts = rng.standard_normal((30, 4))
        pairs = [
            (list(range(15)), list(range(15, 30))),
            (list(range(10)), list(range(20, 30))),
        ]
        out = rotation.means_rotation(pts, pairs)
        assert out.column_names == ["MR1", "MR2", "SVD3", "SVD4"]

    def test_rotation_is_orthonormal(self):
        rng = np.random.default_rng(14)
        pts = rng.standard_normal((40, 5))
        pairs = [(list(range(20)), list(range(20, 40)))]
        out = rotation.means_rotation(pts, pairs)
        np.testing.assert_allclose(
            out.rotation.T @ out.rotation, np.eye(5), atol=1e-10
        )

    def test_errors_on_empty_pairs(self):
        with pytest.raises(RuntimeError, match="without 2 groups"):
            rotation.means_rotation(np.zeros((5, 3)), [])


# ── complete_rotation ────────────────────────────────────────────────────────

class TestCompleteRotation:
    def test_one_axis_matches_reference(self):
        rng = np.random.default_rng(21)
        pts = rng.standard_normal((30, 4))
        pts_c = pts - pts.mean(axis=0)
        pairs = [(list(range(15)), list(range(15, 30)))]
        axes = make_named_axes(pts, pairs)
        out = rotation.complete_rotation(pts_c, axes, ["GMR1"])
        ref = reference_complete_rotation(pts_c, axes)
        # First column = input axis verbatim (no sign flip)
        np.testing.assert_allclose(out.rotation[:, :1], axes, atol=1e-10)
        # Trailing SVD columns match up to sign
        assert_columns_equal_up_to_sign(out.rotation[:, 1:], ref[:, 1:])

    def test_two_axes_matches_reference_with_parallel_deflation(self):
        rng = np.random.default_rng(22)
        pts = rng.standard_normal((50, 6))
        pts_c = pts - pts.mean(axis=0)
        pairs = [
            (list(range(25)), list(range(25, 50))),
            (list(range(0, 10)) + list(range(25, 35)),
             list(range(10, 25)) + list(range(35, 50))),
        ]
        axes = make_named_axes(pts, pairs)
        out = rotation.complete_rotation(pts_c, axes, ["GMR1", "GMR2"])
        ref = reference_complete_rotation(pts_c, axes)
        np.testing.assert_allclose(out.rotation[:, :2], axes, atol=1e-10)
        assert_columns_equal_up_to_sign(out.rotation[:, 2:], ref[:, 2:])

    def test_parallel_deflation_differs_from_sequential_for_nonorthogonal(self):
        """Sanity: confirm rENA's parallel formula differs from sequential
        deflation when the named axes aren't orthogonal — i.e., the
        distinction we ported actually matters."""
        rng = np.random.default_rng(23)
        pts = rng.standard_normal((30, 4))
        pts_c = pts - pts.mean(axis=0)
        # Two non-orthogonal unit-norm axes
        a1 = rng.standard_normal(4); a1 /= np.linalg.norm(a1)
        a2 = rng.standard_normal(4); a2 /= np.linalg.norm(a2)
        assert abs(a1 @ a2) > 0.1, "axes happen to be near-orthogonal; rerun"

        parallel = pts_c - pts_c @ np.column_stack([a1, a2]) @ np.column_stack([a1, a2]).T
        sequential = pts_c - np.outer(pts_c @ a1, a1)
        sequential = sequential - np.outer(sequential @ a2, a2)
        assert not np.allclose(parallel, sequential), (
            "parallel and sequential deflation agree — test data is degenerate"
        )

        # And qe's complete_rotation matches the parallel reference, not sequential.
        axes = np.column_stack([a1, a2])
        out = rotation.complete_rotation(pts_c, axes, ["GMR1", "GMR2"])
        ref = reference_complete_rotation(pts_c, axes)
        np.testing.assert_allclose(out.rotation[:, :2], axes, atol=1e-10)
        assert_columns_equal_up_to_sign(out.rotation[:, 2:], ref[:, 2:])

    @pytest.mark.parametrize("k", [1, 2])
    def test_orthonormal_on_rank_deficient_data(self, k):
        """An all-zero column (a masked connection) costs the data a rank, so
        trailing SVD columns of the deflated data come from its null space --
        which contains the named axes -- and used to nearly duplicate one
        (|cos| ~ 0.99). The fill must stay orthonormal."""
        rng = np.random.default_rng(7)
        pts = rng.standard_normal((40, 6))
        pts_c = pts - pts.mean(axis=0)
        pts_c[:, 1] = 0.0
        axes = np.column_stack([[0.6, 0, 0.8, 0, 0, 0], [0, 0, 0, 1.0, 0, 0]])[:, :k].copy()
        out = rotation.complete_rotation(pts_c, axes, [f"GMR{i + 1}" for i in range(k)])
        R = np.asarray(out.rotation)
        np.testing.assert_allclose(R.T @ R, np.eye(6), atol=1e-10)
        np.testing.assert_allclose(R[:, :k], axes, atol=1e-12)
        # A rotation is a full basis, so the projected variance is the total
        np.testing.assert_allclose((pts_c @ R).var(axis=0, ddof=1).sum(),
                                   pts_c.var(axis=0, ddof=1).sum(), rtol=1e-10)

    def test_orthonormal_with_more_connections_than_units(self):
        rng = np.random.default_rng(11)
        pts = rng.standard_normal((5, 8))
        pts_c = pts - pts.mean(axis=0)          # rank 4 < p = 8
        axes = np.zeros((8, 1)); axes[0, 0] = 1.0
        out = rotation.complete_rotation(pts_c, axes, ["GMR1"])
        R = np.asarray(out.rotation)
        np.testing.assert_allclose(R.T @ R, np.eye(8), atol=1e-10)
        np.testing.assert_allclose(R[:, 0], axes[:, 0], atol=1e-12)

    def test_column_names(self):
        rng = np.random.default_rng(24)
        pts = rng.standard_normal((30, 4))
        pairs = [(list(range(15)), list(range(15, 30)))]
        axes = make_named_axes(pts, pairs)
        out = rotation.complete_rotation(pts - pts.mean(0), axes, ["GMR1"])
        assert out.column_names == ["GMR1", "SVD2", "SVD3", "SVD4"]


# ── orthogonal_svd ───────────────────────────────────────────────────────────

class TestOrthogonalSvd:
    def test_matches_means_rotation_on_same_inputs(self):
        """means_rotation IS orthogonal_svd on centered+deflated data with the
        stacked mean-diff weights — so the two outputs should agree."""
        rng = np.random.default_rng(31)
        pts = rng.standard_normal((30, 4))
        pairs = [
            (list(range(15)), list(range(15, 30))),
            (list(range(10)), list(range(20, 30))),
        ]
        centered = pts - pts.mean(axis=0)
        deflated = centered.copy()
        weights = np.zeros((4, 2))
        for i, (a, b) in enumerate(pairs):
            d = deflated[list(a)].mean(axis=0) - deflated[list(b)].mean(axis=0)
            axis = d / np.linalg.norm(d)
            deflated = rotation.deflate(deflated, axis)
            weights[:, i] = axis
        via_orth = rotation.orthogonal_svd(deflated, weights, ["MR1", "MR2"])
        via_means = rotation.means_rotation(pts, pairs)
        np.testing.assert_allclose(via_orth.rotation, via_means.rotation, atol=1e-12)

    def test_errors_on_label_count_mismatch(self):
        with pytest.raises(RuntimeError, match="named_labels"):
            rotation.orthogonal_svd(np.zeros((5, 4)), np.zeros((4, 2)), ["A"])

    def test_errors_on_data_weight_dim_mismatch(self):
        with pytest.raises(RuntimeError, match="data.n_cols"):
            rotation.orthogonal_svd(np.zeros((5, 4)), np.zeros((3, 1)), ["A"])


# ── RotationResult ───────────────────────────────────────────────────────────

class TestRotationResult:
    def test_attribute_types(self):
        rng = np.random.default_rng(41)
        out = rotation.ena_svd(rng.standard_normal((20, 3)))
        assert isinstance(out, RotationResult)
        assert isinstance(out.rotation, np.ndarray)
        assert out.rotation.dtype == np.float64
        assert isinstance(out.eigenvalues, np.ndarray)
        assert out.eigenvalues.dtype == np.float64
        assert isinstance(out.column_names, list)
        assert all(isinstance(s, str) for s in out.column_names)

    def test_repr_includes_shape_and_labels(self):
        rng = np.random.default_rng(42)
        out = rotation.ena_svd(rng.standard_normal((20, 3)))
        r = repr(out)
        assert "RotationResult" in r and "3x3" in r and "SVD1" in r
