// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rENA.h"
#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// fun_sphere_norm
NumericMatrix fun_sphere_norm(DataFrame dfM);
RcppExport SEXP _rENA_fun_sphere_norm(SEXP dfMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dfM(dfMSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_sphere_norm(dfM));
    return rcpp_result_gen;
END_RCPP
}
// fun_skip_sphere_norm
NumericMatrix fun_skip_sphere_norm(DataFrame dfM);
RcppExport SEXP _rENA_fun_skip_sphere_norm(SEXP dfMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dfM(dfMSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_skip_sphere_norm(dfM));
    return rcpp_result_gen;
END_RCPP
}
// center_data_c
Rcpp::NumericMatrix center_data_c(arma::mat values);
RcppExport SEXP _rENA_center_data_c(SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(center_data_c(values));
    return rcpp_result_gen;
END_RCPP
}
// triIndices
arma::umat triIndices(int len, int row);
RcppExport SEXP _rENA_triIndices(SEXP lenSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    rcpp_result_gen = Rcpp::wrap(triIndices(len, row));
    return rcpp_result_gen;
END_RCPP
}
// getN
int getN(arma::mat normed);
RcppExport SEXP _rENA_getN(SEXP normedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    rcpp_result_gen = Rcpp::wrap(getN(normed));
    return rcpp_result_gen;
END_RCPP
}
// lws_lsq_positions
Rcpp::List lws_lsq_positions(arma::mat adjMats, arma::mat t, int numDims);
RcppExport SEXP _rENA_lws_lsq_positions(SEXP adjMatsSEXP, SEXP tSEXP, SEXP numDimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type adjMats(adjMatsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type numDims(numDimsSEXP);
    rcpp_result_gen = Rcpp::wrap(lws_lsq_positions(adjMats, t, numDims));
    return rcpp_result_gen;
END_RCPP
}
// linderoth_pos_es
Rcpp::List linderoth_pos_es(Eigen::MatrixXd adjMats, Eigen::MatrixXd t, int numDims);
RcppExport SEXP _rENA_linderoth_pos_es(SEXP adjMatsSEXP, SEXP tSEXP, SEXP numDimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type adjMats(adjMatsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type numDims(numDimsSEXP);
    rcpp_result_gen = Rcpp::wrap(linderoth_pos_es(adjMats, t, numDims));
    return rcpp_result_gen;
END_RCPP
}
// merge_columns_c
std::vector<std::string> merge_columns_c(DataFrame df, CharacterVector cols, std::string sep);
RcppExport SEXP _rENA_merge_columns_c(SEXP dfSEXP, SEXP colsSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< std::string >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_columns_c(df, cols, sep));
    return rcpp_result_gen;
END_RCPP
}
// rows_to_co_occurrences
arma::mat rows_to_co_occurrences(DataFrame df, bool binary);
static SEXP _rENA_rows_to_co_occurrences_try(SEXP dfSEXP, SEXP binarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    rcpp_result_gen = Rcpp::wrap(rows_to_co_occurrences(df, binary));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rENA_rows_to_co_occurrences(SEXP dfSEXP, SEXP binarySEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rENA_rows_to_co_occurrences_try(dfSEXP, binarySEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// ref_window_df
DataFrame ref_window_df(DataFrame df, float windowSize, float windowForward, bool binary, bool binaryStanzas);
static SEXP _rENA_ref_window_df_try(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP windowForwardSEXP, SEXP binarySEXP, SEXP binaryStanzasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< float >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< float >::type windowForward(windowForwardSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< bool >::type binaryStanzas(binaryStanzasSEXP);
    rcpp_result_gen = Rcpp::wrap(ref_window_df(df, windowSize, windowForward, binary, binaryStanzas));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rENA_ref_window_df(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP windowForwardSEXP, SEXP binarySEXP, SEXP binaryStanzasSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rENA_ref_window_df_try(dfSEXP, windowSizeSEXP, windowForwardSEXP, binarySEXP, binaryStanzasSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// ref_window_lag
DataFrame ref_window_lag(DataFrame df, int windowSize, bool binary);
static SEXP _rENA_ref_window_lag_try(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP binarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    rcpp_result_gen = Rcpp::wrap(ref_window_lag(df, windowSize, binary));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rENA_ref_window_lag(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP binarySEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rENA_ref_window_lag_try(dfSEXP, windowSizeSEXP, binarySEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// ref_window_sum
DataFrame ref_window_sum(DataFrame df, bool binary);
RcppExport SEXP _rENA_ref_window_sum(SEXP dfSEXP, SEXP binarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    rcpp_result_gen = Rcpp::wrap(ref_window_sum(df, binary));
    return rcpp_result_gen;
END_RCPP
}
// svector_to_ut
std::vector<std::string> svector_to_ut(std::vector<std::string> v);
RcppExport SEXP _rENA_svector_to_ut(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(svector_to_ut(v));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _rENA_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::mat(*rows_to_co_occurrences)(DataFrame,bool)");
        signatures.insert("DataFrame(*ref_window_df)(DataFrame,float,float,bool,bool)");
        signatures.insert("DataFrame(*ref_window_lag)(DataFrame,int,bool)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _rENA_RcppExport_registerCCallable() { 
    R_RegisterCCallable("rENA", "_rENA_rows_to_co_occurrences", (DL_FUNC)_rENA_rows_to_co_occurrences_try);
    R_RegisterCCallable("rENA", "_rENA_ref_window_df", (DL_FUNC)_rENA_ref_window_df_try);
    R_RegisterCCallable("rENA", "_rENA_ref_window_lag", (DL_FUNC)_rENA_ref_window_lag_try);
    R_RegisterCCallable("rENA", "_rENA_RcppExport_validate", (DL_FUNC)_rENA_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_rENA_fun_sphere_norm", (DL_FUNC) &_rENA_fun_sphere_norm, 1},
    {"_rENA_fun_skip_sphere_norm", (DL_FUNC) &_rENA_fun_skip_sphere_norm, 1},
    {"_rENA_center_data_c", (DL_FUNC) &_rENA_center_data_c, 1},
    {"_rENA_triIndices", (DL_FUNC) &_rENA_triIndices, 2},
    {"_rENA_getN", (DL_FUNC) &_rENA_getN, 1},
    {"_rENA_lws_lsq_positions", (DL_FUNC) &_rENA_lws_lsq_positions, 3},
    {"_rENA_linderoth_pos_es", (DL_FUNC) &_rENA_linderoth_pos_es, 3},
    {"_rENA_merge_columns_c", (DL_FUNC) &_rENA_merge_columns_c, 3},
    {"_rENA_rows_to_co_occurrences", (DL_FUNC) &_rENA_rows_to_co_occurrences, 2},
    {"_rENA_ref_window_df", (DL_FUNC) &_rENA_ref_window_df, 5},
    {"_rENA_ref_window_lag", (DL_FUNC) &_rENA_ref_window_lag, 3},
    {"_rENA_ref_window_sum", (DL_FUNC) &_rENA_ref_window_sum, 2},
    {"_rENA_svector_to_ut", (DL_FUNC) &_rENA_svector_to_ut, 1},
    {"_rENA_RcppExport_registerCCallable", (DL_FUNC) &_rENA_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rENA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
