// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dfvector_to_ut
DataFrame dfvector_to_ut(DataFrame v, CharacterVector nms);
RcppExport SEXP rENA_dfvector_to_ut(SEXP vSEXP, SEXP nmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type v(vSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nms(nmsSEXP);
    __result = Rcpp::wrap(dfvector_to_ut(v, nms));
    return __result;
END_RCPP
}
// count_if
int count_if(LogicalVector x);
RcppExport SEXP rENA_count_if(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    __result = Rcpp::wrap(count_if(x));
    return __result;
END_RCPP
}
// vecmin
int vecmin(NumericVector x);
RcppExport SEXP rENA_vecmin(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(vecmin(x));
    return __result;
END_RCPP
}
// vecmax
int vecmax(NumericVector x);
RcppExport SEXP rENA_vecmax(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(vecmax(x));
    return __result;
END_RCPP
}
// logicalToColNums
NumericVector logicalToColNums(LogicalVector lv);
RcppExport SEXP rENA_logicalToColNums(SEXP lvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< LogicalVector >::type lv(lvSEXP);
    __result = Rcpp::wrap(logicalToColNums(lv));
    return __result;
END_RCPP
}
// rowSumsC
NumericVector rowSumsC(NumericMatrix x);
RcppExport SEXP rENA_rowSumsC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(rowSumsC(x));
    return __result;
END_RCPP
}
// fixIt
arma::mat fixIt(DataFrame df);
RcppExport SEXP rENA_fixIt(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    __result = Rcpp::wrap(fixIt(df));
    return __result;
END_RCPP
}
// sphere_norm
arma::mat sphere_norm(arma::mat m);
RcppExport SEXP rENA_sphere_norm(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(sphere_norm(m));
    return __result;
END_RCPP
}
// dont_sphere_norm
arma::mat dont_sphere_norm(arma::mat m);
RcppExport SEXP rENA_dont_sphere_norm(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(dont_sphere_norm(m));
    return __result;
END_RCPP
}
// normIt
arma::mat normIt(DataFrame df);
RcppExport SEXP rENA_normIt(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    __result = Rcpp::wrap(normIt(df));
    return __result;
END_RCPP
}
// pca
Rcpp::NumericMatrix pca(arma::mat m, int dims);
RcppExport SEXP rENA_pca(SEXP mSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type dims(dimsSEXP);
    __result = Rcpp::wrap(pca(m, dims));
    return __result;
END_RCPP
}
// centerData
Rcpp::NumericMatrix centerData(arma::mat values);
RcppExport SEXP rENA_centerData(SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type values(valuesSEXP);
    __result = Rcpp::wrap(centerData(values));
    return __result;
END_RCPP
}
// centerDataRotated
Rcpp::NumericMatrix centerDataRotated(arma::mat centeredValues, arma::mat rotated);
RcppExport SEXP rENA_centerDataRotated(SEXP centeredValuesSEXP, SEXP rotatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type centeredValues(centeredValuesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    __result = Rcpp::wrap(centerDataRotated(centeredValues, rotated));
    return __result;
END_RCPP
}
// eq_pos
Rcpp::NumericMatrix eq_pos(Rcpp::CharacterVector names, Rcpp::CharacterMatrix labels, arma::mat rotated, bool plusOne);
RcppExport SEXP rENA_eq_pos(SEXP namesSEXP, SEXP labelsSEXP, SEXP rotatedSEXP, SEXP plusOneSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterMatrix >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    Rcpp::traits::input_parameter< bool >::type plusOne(plusOneSEXP);
    __result = Rcpp::wrap(eq_pos(names, labels, rotated, plusOne));
    return __result;
END_RCPP
}
// triIndices
arma::uvec triIndices(int len, int row);
RcppExport SEXP rENA_triIndices(SEXP lenSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    __result = Rcpp::wrap(triIndices(len, row));
    return __result;
END_RCPP
}
// getcor
double getcor(arma::mat dists, arma::mat normed, arma::mat x, arma::uvec NtriOne, arma::uvec NtriTwo, arma::uvec KtriOne, arma::uvec KtriTwo, int dim);
RcppExport SEXP rENA_getcor(SEXP distsSEXP, SEXP normedSEXP, SEXP xSEXP, SEXP NtriOneSEXP, SEXP NtriTwoSEXP, SEXP KtriOneSEXP, SEXP KtriTwoSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type NtriOne(NtriOneSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type NtriTwo(NtriTwoSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type KtriOne(KtriOneSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type KtriTwo(KtriTwoSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    __result = Rcpp::wrap(getcor(dists, normed, x, NtriOne, NtriTwo, KtriOne, KtriTwo, dim));
    return __result;
END_RCPP
}
// single_optim
//arma::vec List single_optim(arma::mat normed, arma::mat dists, arma::mat rotated, arma::uvec NtriOne, arma::uvec NtriTwo, arma::uvec KtriOne, arma::uvec KtriTwo, int dim, double N);
RcppExport SEXP rENA_single_optim(SEXP normedSEXP, SEXP distsSEXP, SEXP rotatedSEXP, SEXP NtriOneSEXP, SEXP NtriTwoSEXP, SEXP KtriOneSEXP, SEXP KtriTwoSEXP, SEXP dimSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type NtriOne(NtriOneSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type NtriTwo(NtriTwoSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type KtriOne(KtriOneSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type KtriTwo(KtriTwoSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    __result = Rcpp::wrap(single_optim(normed, dists, rotated, NtriOne, NtriTwo, KtriOne, KtriTwo, dim, N));
    return __result;
END_RCPP
}
// getN
int getN(arma::mat normed);
RcppExport SEXP rENA_getN(SEXP normedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    __result = Rcpp::wrap(getN(normed));
    return __result;
END_RCPP
}
// getK
int getK(arma::mat normed);
RcppExport SEXP rENA_getK(SEXP normedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    __result = Rcpp::wrap(getK(normed));
    return __result;
END_RCPP
}
// do_opt
NumericMatrix do_opt(arma::mat normed, arma::mat dists, arma::mat rotated, int num_samples, int num_dims);
RcppExport SEXP rENA_do_opt(SEXP normedSEXP, SEXP distsSEXP, SEXP rotatedSEXP, SEXP num_samplesSEXP, SEXP num_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    __result = Rcpp::wrap(do_opt(normed, dists, rotated, num_samples, num_dims));
    return __result;
END_RCPP
}
// getRotationDistances
arma::mat getRotationDistances(arma::mat rotated);
RcppExport SEXP rENA_getRotationDistances(SEXP rotatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    __result = Rcpp::wrap(getRotationDistances(rotated));
    return __result;
END_RCPP
}
// get_optimized_node_pos
Rcpp::List get_optimized_node_pos(arma::mat normedFiltered, NumericMatrix opted, int num_dims, int num_samples, int max_iter, bool return_all);
RcppExport SEXP rENA_get_optimized_node_pos(SEXP normedFilteredSEXP, SEXP optedSEXP, SEXP num_dimsSEXP, SEXP num_samplesSEXP, SEXP max_iterSEXP, SEXP return_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normedFiltered(normedFilteredSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type opted(optedSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type return_all(return_allSEXP);
    __result = Rcpp::wrap(get_optimized_node_pos(normedFiltered, opted, num_dims, num_samples, max_iter, return_all));
    return __result;
END_RCPP
}
// fastLm
List fastLm(const arma::vec& y, const arma::mat& X);
RcppExport SEXP rENA_fastLm(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    __result = Rcpp::wrap(fastLm(y, X));
    return __result;
END_RCPP
}
// summary_fastLm_c
//arma::vec List summary_fastLm_c(List object);
RcppExport SEXP rENA_summary_fastLm_c(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type object(objectSEXP);
    __result = Rcpp::wrap(summary_fastLm_c(object));
    return __result;
END_RCPP
}
// lm_
List lm_(NumericMatrix x);
RcppExport SEXP rENA_lm_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(lm_(x));
    return __result;
END_RCPP
}
// full_opt
Rcpp::List full_opt(arma::mat normed, arma::mat rotated, Rcpp::List optim_nodes, int dims, int num_samples);
RcppExport SEXP rENA_full_opt(SEXP normedSEXP, SEXP rotatedSEXP, SEXP optim_nodesSEXP, SEXP dimsSEXP, SEXP num_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rotated(rotatedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type optim_nodes(optim_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    __result = Rcpp::wrap(full_opt(normed, rotated, optim_nodes, dims, num_samples));
    return __result;
END_RCPP
}
// testNO
bool testNO(arma::mat normed, arma::vec rotated, arma::vec soln);
RcppExport SEXP rENA_testNO(SEXP normedSEXP, SEXP rotatedSEXP, SEXP solnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type normed(normedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rotated(rotatedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type soln(solnSEXP);
    __result = Rcpp::wrap(testNO(normed, rotated, soln));
    return __result;
END_RCPP
}
// get_cor
arma::mat get_cor(arma::vec dists, arma::vec cents);
RcppExport SEXP rENA_get_cor(SEXP distsSEXP, SEXP centsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cents(centsSEXP);
    __result = Rcpp::wrap(get_cor(dists, cents));
    return __result;
END_RCPP
}
// run_optimC
bool run_optimC();
RcppExport SEXP rENA_run_optimC() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(run_optimC());
    return __result;
END_RCPP
}
// calc_cor
double calc_cor(arma::vec x, List set, int dim);
RcppExport SEXP rENA_calc_cor(SEXP xSEXP, SEXP setSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type set(setSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    __result = Rcpp::wrap(calc_cor(x, set, dim));
    return __result;
END_RCPP
}
// soln_MPS
arma::vec soln_MPS(arma::mat x);
RcppExport SEXP rENA_soln_MPS(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(soln_MPS(x));
    return __result;
END_RCPP
}
// soln_calc
double soln_calc(arma::vec coeff, arma::mat xi, arma::mat ti, arma::mat w, int dim);
RcppExport SEXP rENA_soln_calc(SEXP coeffSEXP, SEXP xiSEXP, SEXP tiSEXP, SEXP wSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    __result = Rcpp::wrap(soln_calc(coeff, xi, ti, w, dim));
    return __result;
END_RCPP
}
// ref_window_df
DataFrame ref_window_df(DataFrame df, int windowSize, bool binary, bool useDiaganol);
RcppExport SEXP rENA_ref_window_df(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP binarySEXP, SEXP useDiaganolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< bool >::type useDiaganol(useDiaganolSEXP);
    __result = Rcpp::wrap(ref_window_df(df, windowSize, binary, useDiaganol));
    return __result;
END_RCPP
}
// ref_window_df2
DataFrame ref_window_df2(DataFrame df, int windowSize, bool binary, bool useDiaganol);
RcppExport SEXP rENA_ref_window_df2(SEXP dfSEXP, SEXP windowSizeSEXP, SEXP binarySEXP, SEXP useDiaganolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< bool >::type useDiaganol(useDiaganolSEXP);
    __result = Rcpp::wrap(ref_window_df2(df, windowSize, binary, useDiaganol));
    return __result;
END_RCPP
}
// ref_window_sum
DataFrame ref_window_sum(DataFrame df, bool binary);
RcppExport SEXP rENA_ref_window_sum(SEXP dfSEXP, SEXP binarySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    __result = Rcpp::wrap(ref_window_sum(df, binary));
    return __result;
END_RCPP
}
// svector_to_ut
std::vector<std::string> svector_to_ut(std::vector<std::string> v);
RcppExport SEXP rENA_svector_to_ut(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type v(vSEXP);
    __result = Rcpp::wrap(svector_to_ut(v));
    return __result;
END_RCPP
}
// vector_to_ut_full
std::vector<int> vector_to_ut_full(std::vector<int> v);
RcppExport SEXP rENA_vector_to_ut_full(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<int> >::type v(vSEXP);
    __result = Rcpp::wrap(vector_to_ut_full(v));
    return __result;
END_RCPP
}
// vector_to_ut
std::vector<int> vector_to_ut(std::vector<int> v);
RcppExport SEXP rENA_vector_to_ut(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<int> >::type v(vSEXP);
    __result = Rcpp::wrap(vector_to_ut(v));
    return __result;
END_RCPP
}
