#' Calculate the Peak Ground Diversity Window
#'
#' This function acts as a wrapper to identify the sliding window size that yields
#' the highest (peak) ground diversity/entropy for a given dataset.
#'
#' @param data A data.frame or data.table containing the conversation data.
#' @param codeNames A character vector of column names representing the binary codes.
#' @param conversation_cols A character vector of column names that define unique conversations.
#' @param max_window An integer specifying the maximum window size to evaluate. Default is 20.
#'
#' @return An integer representing the window size that maximizes ground entropy.
#' @export
#'
#' @examples
#' \dontrun{
#' peak_w <- ena.gd.window(data = my_data,
#'                         codeNames = c("CodeA", "CodeB"),
#'                         conversation_cols = "ConversationID",
#'                         max_window = 15)
#' }
ena.gd.window <- function(data, codeNames, conversation_cols, max_window = 20) {
  gd <- ena.ground.diversity(data, codeNames, conversation_cols, max_window)
  return(gd$peaks$peak_window)
}

#' Calculate Ground Diversity (Entropy) Curves and Peaks
#'
#' Evaluates the diversity of "ground types" (combinations of active codes)
#' across a series of sliding window sizes. It returns both the curves and the
#' peak window values.
#'
#' @param data A data.frame or data.table containing the conversation data.
#' @param codeNames A character vector of column names representing the binary codes.
#' @param conversation_cols A character vector of column names that define unique conversations.
#' @param max_window An integer specifying the maximum window size to evaluate. Default is 20.
#'
#' @return A list containing three elements:
#' \describe{
#'   \item{curves}{A data.table containing aggregated entropy curves across windows.}
#'   \item{peaks}{A data.table highlighting the window size(s) where entropy peaked.}
#'   \item{conversation_curves}{A data.table showing calculated entropy per individual conversation per window.}
#' }
#' @export
#'
#' @examples
#' \dontrun{
#' gd_results <- ena.ground.diversity(data = my_data,
#'                                    codeNames = c("CodeA", "CodeB"),
#'                                    conversation_cols = "ConversationID")
#' }
ena.ground.diversity <- function(data, codeNames, conversation_cols, max_window = 20) {
  num_codes <- length(codeNames)

  counts <- ground.type.counts(
    data = data,
    codeNames = codeNames,
    conversation_cols = conversation_cols,
    max_window = max_window
  )

  ground.entropy.curves(
    counts = counts,
    conversation_cols = conversation_cols,
    num_codes = num_codes,
    methods = "mean",
    normalize = TRUE
  )
}

#' Calculate Entropy Curves from Ground Type Counts
#'
#' Internal helper function that takes ground type frequencies and computes Shannon entropy
#' across different aggregation methods (mean, weighted, or pooled) and window sizes.
#'
#' @param counts A data.table generated by \code{\link{ground.type.counts}}.
#' @param conversation_cols A character vector of column names defining unique conversations.
#' @param num_codes An integer representing the total number of unique codes (used for normalization base \eqn{2^C}).
#' @param group_cols A character vector of columns to group by (e.g., experimental conditions). Default is NULL.
#' @param methods A character vector specifying which aggregation methods to calculate. Options include "mean", "weighted", and "pooled". Default is all three.
#' @param normalize Logical; if TRUE (default), entropy is normalized to a \eqn{[0, 1]} scale.
#'
#' @return A list containing:
#' \describe{
#'   \item{curves}{Aggregated entropy metrics across windows and methods.}
#'   \item{peaks}{The optimal window size that maximized entropy for each method.}
#'   \item{conversation_curves}{Entropy calculations mapped back to individual conversations.}
#' }
#' @keywords internal
ground.entropy.curves <- function(
    counts,
    conversation_cols,
    num_codes,
    group_cols = NULL,
    methods = c("mean", "weighted", "pooled"),
    normalize = TRUE
) {
  dt <- as.data.table(counts)

  if (is.null(group_cols)) {
    dt[, .group := "all"]
    group_cols <- ".group"
  }

  log_base <- if (normalize) log(2^num_codes) else 1

  conv_entropy <- dt[
    ,
    {
      p <- count / sum(count)
      .(
        entropy = -sum(p * log(p)) / log_base,
        n_unique = .N,
        n_obs = unique(n_obs)
      )
    },
    by = c(conversation_cols, group_cols, "window")
  ]

  results <- list()

  # --- Mean ---
  if ("mean" %in% methods) {
    tmp <- conv_entropy[
      ,
      .(
        entropy = mean(entropy),
        n_unique = mean(n_unique),
        n_conversations = .N
      ),
      by = c(group_cols, "window")
    ]
    tmp[, method := "mean"]
    results[[length(results) + 1]] <- tmp
  }

  # --- Weighted ---
  if ("weighted" %in% methods) {
    tmp <- conv_entropy[
      ,
      .(
        entropy = weighted.mean(entropy, n_obs),
        n_unique = weighted.mean(n_unique, n_obs),
        n_conversations = .N
      ),
      by = c(group_cols, "window")
    ]
    tmp[, method := "weighted"]
    results[[length(results) + 1]] <- tmp
  }

  # --- Pooled ---
  if ("pooled" %in% methods) {
    tmp <- dt[
      ,
      .(count = sum(count)),
      by = c(group_cols, "window", "ground_type")
    ][
      ,
      {
        p <- count / sum(count)
        .(
          entropy = -sum(p * log(p)) / log_base,
          n_unique = .N
        )
      },
      by = c(group_cols, "window")
    ]
    tmp[, method := "pooled"]
    results[[length(results) + 1]] <- tmp
  }

  curves <- rbindlist(results, fill = TRUE)

  peaks <- curves[
    ,
    .SD[which.max(entropy)][1],
    by = c(group_cols, "method")
  ][
    ,
    .(
      peak_window = window,
      peak_entropy = entropy,
      method = method
    ),
    by = group_cols
  ]

  list(
    curves = curves,
    peaks = peaks,
    conversation_curves = conv_entropy
  )
}

#' Generate Binary-Encoded Ground Type Counts
#'
#' Compiles the frequencies of unique co-occurrence patterns ("ground types")
#' across multiple sliding window sizes, using fast column-wise rolling maximum operations.
#'
#' @param data A data.frame or data.table.
#' @param codeNames A character vector of column names representing the binary codes.
#' @param conversation_cols A character vector of column names that define unique conversations.
#' @param max_window An integer specifying the maximum window size to evaluate. Default is 20.
#'
#' @return A data.table containing the counts of ground types per conversation per window size.
#' @keywords internal
ground.type.counts <- function(
    data,
    codeNames,
    conversation_cols,
    max_window = 20
) {
  stopifnot(all(codeNames %in% names(data)))
  stopifnot(all(conversation_cols %in% names(data)))

  dt <- data.table::as.data.table(data)

  # Ground-type encoding assumes each code is a binary presence/absence flag;
  # non-binary values would corrupt the bit-weighted `ground_type` id.
  code_vals <- unique(as.vector(as.matrix(dt[, ..codeNames])))
  if (!all(code_vals %in% c(0, 1))) {
    stop("All codeNames columns must be binary (0/1); found non-binary values.")
  }
  bit_weights <- 2^(seq_along(codeNames) - 1)

  out <- list()

  for (w in seq_len(max_window)) {
    temp_dt <- dt[, c(..conversation_cols, ..codeNames)]

    # The rolling max of a binary code column is simply "is any code active in
    # the window", i.e. frollsum(col, w) > 0. frollsum runs in C, whereas
    # frollapply(col, w, max) invokes an R closure at every window position, so
    # this is ~2 orders of magnitude faster for the same result.
    temp_dt[, (codeNames) := lapply(.SD, function(col) {
      rolled <- as.numeric(data.table::frollsum(col, w, align = "right") > 0)
      na_indices <- which(is.na(rolled))
      if (length(na_indices) > 0) {
        rolled[na_indices] <- cummax(col[na_indices])
      }
      return(rolled)
    }), by = conversation_cols, .SDcols = codeNames]

    g_matrix <- as.matrix(temp_dt[, ..codeNames])
    temp_dt[, ground_type := as.vector(g_matrix %*% bit_weights)]

    counts <- temp_dt[
      ,
      .(count = .N),
      by = c(conversation_cols, "ground_type")
    ]

    counts[, window := w]
    counts[, n_obs := sum(count), by = conversation_cols]

    out[[w]] <- counts
  }

  data.table::rbindlist(out, use.names = TRUE)
}
