# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the upper triangle of a vector of integers  if it
#' were converted to a matrix. This actually skips creating the
#' matrix, by only multiplying the necesseary indices of the
#' vector.
#'
#' @param v - A vector of integers
#' @export
dfvector_to_ut <- function(v, nms) {
    .Call('rENA_dfvector_to_ut', PACKAGE = 'rENA', v, nms)
}

count_if <- function(x) {
    .Call('rENA_count_if', PACKAGE = 'rENA', x)
}

vecmin <- function(x) {
    .Call('rENA_vecmin', PACKAGE = 'rENA', x)
}

vecmax <- function(x) {
    .Call('rENA_vecmax', PACKAGE = 'rENA', x)
}

logicalToColNums <- function(lv) {
    .Call('rENA_logicalToColNums', PACKAGE = 'rENA', lv)
}

rowSumsC <- function(x) {
    .Call('rENA_rowSumsC', PACKAGE = 'rENA', x)
}

toNumericMatrix <- function(x) {
    .Call('rENA_toNumericMatrix', PACKAGE = 'rENA', x)
}

c_cor <- function(mat) {
    .Call('rENA_c_cor', PACKAGE = 'rENA', mat)
}

sphere_norm_c <- function(dfM) {
    .Call('rENA_sphere_norm_c', PACKAGE = 'rENA', dfM)
}

dont_sphere_norm_c <- function(dfM) {
    .Call('rENA_dont_sphere_norm_c', PACKAGE = 'rENA', dfM)
}

normIt <- function(df) {
    .Call('rENA_normIt', PACKAGE = 'rENA', df)
}

pca <- function(m, dims = 2L) {
    .Call('rENA_pca', PACKAGE = 'rENA', m, dims)
}

center_data_c <- function(values) {
    .Call('rENA_center_data_c', PACKAGE = 'rENA', values)
}

eq_pos <- function(names, labels, rotated, plusOne) {
    .Call('rENA_eq_pos', PACKAGE = 'rENA', names, labels, rotated, plusOne)
}

triIndices <- function(len, row = 0L) {
    .Call('rENA_triIndices', PACKAGE = 'rENA', len, row)
}

getcor <- function(dists, normed, x, NtriOne, NtriTwo, KtriOne, KtriTwo, dim = 0L) {
    .Call('rENA_getcor', PACKAGE = 'rENA', dists, normed, x, NtriOne, NtriTwo, KtriOne, KtriTwo, dim)
}

getN <- function(normed) {
    .Call('rENA_getN', PACKAGE = 'rENA', normed)
}

getK <- function(normed) {
    .Call('rENA_getK', PACKAGE = 'rENA', normed)
}

getRotationDistances <- function(rotated) {
    .Call('rENA_getRotationDistances', PACKAGE = 'rENA', rotated)
}

get_optimized_node_pos <- function(normedFiltered, opted, num_dims = 2L, num_samples = 3L, max_iter = 1000L, return_all = TRUE) {
    .Call('rENA_get_optimized_node_pos', PACKAGE = 'rENA', normedFiltered, opted, num_dims, num_samples, max_iter, return_all)
}

fastLm <- function(y, X) {
    .Call('rENA_fastLm', PACKAGE = 'rENA', y, X)
}

summary_fastLm_c <- function(object) {
    .Call('rENA_summary_fastLm_c', PACKAGE = 'rENA', object)
}

lm_ <- function(x) {
    .Call('rENA_lm_', PACKAGE = 'rENA', x)
}

full_opt <- function(normed, rotated, optim_nodes, dims = 2L, num_samples = 3L, checkUnique = FALSE) {
    .Call('rENA_full_opt', PACKAGE = 'rENA', normed, rotated, optim_nodes, dims, num_samples, checkUnique)
}

get_cor <- function(dists, cents) {
    .Call('rENA_get_cor', PACKAGE = 'rENA', dists, cents)
}

run_optimC <- function() {
    .Call('rENA_run_optimC', PACKAGE = 'rENA')
}

calc_cor <- function(x, set, dim) {
    .Call('rENA_calc_cor', PACKAGE = 'rENA', x, set, dim)
}

soln_MPS <- function(x) {
    .Call('rENA_soln_MPS', PACKAGE = 'rENA', x)
}

soln_calc <- function(coeff, xi, ti, w, dim) {
    .Call('rENA_soln_calc', PACKAGE = 'rENA', coeff, xi, ti, w, dim)
}

remove_zero_rows <- function(toFilter) {
    .Call('rENA_remove_zero_rows', PACKAGE = 'rENA', toFilter)
}

remove_zero_rows_by <- function(toFilter, indices) {
    .Call('rENA_remove_zero_rows_by', PACKAGE = 'rENA', toFilter, indices)
}

#' @title ref_window_df2
#' @name ref_window_df2
#' @param v - A dataframe
#' @param nms - A vector of characters used for colnames of returned DataFrame
#' @export
ref_window_df_ <- function(df, windowSize = 0L, binary = TRUE, useDiaganol = FALSE) {
    .Call('rENA_ref_window_df_', PACKAGE = 'rENA', df, windowSize, binary, useDiaganol)
}

#' @title ref_window_df
#' @name ref_window_df
#' @param v - A dataframe
#' @param nms - A vector of characters used for colnames of returned DataFrame
#' @export
ref_window_df <- function(df, windowSize = 0L, binary = TRUE, useDiaganol = FALSE) {
    .Call('rENA_ref_window_df', PACKAGE = 'rENA', df, windowSize, binary, useDiaganol)
}

ref_window_df2 <- function(df, windowSize = 1L, binary = TRUE, useDiaganol = FALSE) {
    .Call('rENA_ref_window_df2', PACKAGE = 'rENA', df, windowSize, binary, useDiaganol)
}

ref_window_from_conv <- function(df, convs, windowSize = 1L, binary = TRUE, useDiaganol = FALSE) {
    .Call('rENA_ref_window_from_conv', PACKAGE = 'rENA', df, convs, windowSize, binary, useDiaganol)
}

#' @name ref_window_sum
#' @title ref_window_sum
#' @param v - A dataframe
#' @param nms - A vector of characters used for colnames of returned DataFrame
#' @export
ref_window_sum <- function(df, binary = TRUE) {
    .Call('rENA_ref_window_sum', PACKAGE = 'rENA', df, binary)
}

#' Calculates the upper triangle of a vector of integers  if it
#' were converted to a matrix. This actually skips creating the
#' matrix, by only multiplying the necesseary indices of the
#' vector.
#'
#' @param v - A vector of integers
#' @export
svector_to_ut <- function(v) {
    .Call('rENA_svector_to_ut', PACKAGE = 'rENA', v)
}

#' Calculates the upper triangle (including the diaganol) of a
#' vector of integers  if it were converted to a matrix. This
#' actually skips creating the matrix, by only multiplying the
#' necesseary indices of the vector.
#'
#' @param v - A vector of integers
#' @export
vector_to_ut_full <- function(v) {
    .Call('rENA_vector_to_ut_full', PACKAGE = 'rENA', v)
}

#' Calculates the upper triangle of a vector of integers  if it
#' were converted to a matrix. This actually skips creating the
#' matrix, by only multiplying the necesseary indices of the
#' vector.
#'
#' @param v - A vector of integers
#' @export
vector_to_ut <- function(v) {
    .Call('rENA_vector_to_ut', PACKAGE = 'rENA', v)
}

