/**
 * Generalized means rotation (GMR) stays orthonormal on a masked model and
 * matches R.
 *
 * A code mask zeroes connection columns, which makes the data rank-deficient.
 * libqe's complete_rotation() used to fill the trailing axes with SVD columns
 * from the deflated data's null space -- which contains the named axes -- so a
 * masked GMR rotation could nearly duplicate GMR1 (|cos| ~ 0.95) and count its
 * variance twice. Fixed in libqe's complete_rotation (null-space columns are
 * orthogonalised against the named axes).
 *
 * Fixture test/fixtures/gmr-masked-rs.json is generated by
 * test/fixtures/gmr-masked-rs.R (run from the repo root, with a libqe that has
 * the fix) from inst/extdata/rs.data.csv:
 *   acc <- ena.accumulate.data(units = c("Condition","UserName"),
 *            conversation = c("Condition","GroupName"), codes, window.size.back = 4)
 *   acc$connection.counts[["Data & Technical.Constraints"]] <- 0   # the mask
 *   ena.make.set(acc, rotation.by = ena.rotate.by.generalized,
 *     rotation.params = list(x_var = "Condition",
 *                            select_2_groups = c("FirstGame","SecondGame")))
 *   → points[, 1:2], model$variance[1:4]
 */
import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import loadENA from '../src/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EXTDATA   = path.resolve(__dirname, '../../inst/extdata');
const FIXTURE   = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/gmr-masked-rs.json'), 'utf8'));

function parseCSVRow(line) {
    const result = [];
    let current  = '';
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === '\r') continue;
        if (ch === '"') {
            if (inQuotes && line[i + 1] === '"') { current += '"'; i++; }
            else inQuotes = !inQuotes;
        } else if (ch === ',' && !inQuotes) {
            result.push(current);
            current = '';
        } else {
            current += ch;
        }
    }
    result.push(current);
    return result;
}

function parseCSV(text) {
    const lines   = text.split('\n').filter(l => l.trim().replace(/\r/g, '') !== '');
    const headers = parseCSVRow(lines[0]);
    return lines.slice(1).map(line => {
        const values = parseCSVRow(line);
        return Object.fromEntries(headers.map((h, i) => [h, values[i] ?? '']));
    });
}

const CODES = ['Data', 'Technical Constraints', 'Performance Parameters',
               'Client and Consultant Requests', 'Design Reasoning', 'Collaboration'];
const BASE  = { codes: CODES, units: ['Condition', 'UserName'],
                conversations: ['Condition', 'GroupName'], window: 4, dims: 15 };

let ena, rows, gParams;
beforeAll(async () => {
    ena  = await loadENA();
    rows = parseCSV(fs.readFileSync(path.join(EXTDATA, 'rs.data.csv'), 'utf8'));
    const seen = new Map();
    for (const r of rows) {
        const key = BASE.units.map(c => String(r[c])).join('__');
        if (!seen.has(key)) seen.set(key, r);
    }
    const cond = [...seen.values()].map(r => r.Condition);
    const dummy = Float64Array.from(cond.map(v => (v === 'SecondGame' ? 1 : 0)));
    gParams = {
        xModelMatrix: dummy, xmRows: cond.length, xmCols: 1,
        xTarget: dummy, x1Cols: Int32Array.from([0]), xCategorical: true, xNGroups: 2,
        xSubset: Int32Array.from(cond.map((_, i) => i)), hasY: false,
    };
});

// Mask the Data & Technical Constraints connection.
const MASK = CODES.map(() => CODES.map(() => 1));
MASK[0][1] = MASK[1][0] = 0;

function maxOffDiagonal(fit) {
    const R = fit.rotationMatrix, p = fit.nConnections, k = fit.dims;
    let max = 0;
    for (let i = 0; i < k; i++)
        for (let j = i + 1; j < k; j++) {
            let s = 0;
            for (let r = 0; r < p; r++) s += R[r * k + i] * R[r * k + j];
            max = Math.max(max, Math.abs(s));
        }
    return max;
}

test('masked GMR rotation is orthonormal', () => {
    const fit = ena.fit(rows, { ...BASE, rotation: 'generalized', gParams, codeMask: MASK });
    expect(fit.dims).toBe(15);
    expect(maxOffDiagonal(fit)).toBeLessThan(1e-10);
});

test('masked GMR matches R ena.rotate.by.generalized (points, variance)', () => {
    const fit = ena.fit(rows, { ...BASE, rotation: 'generalized', gParams, codeMask: MASK });
    const idx = FIXTURE.units.map(u => fit.model.unitLabels.indexOf(u.replace('::', '__')));
    expect(idx.every(i => i >= 0)).toBe(true);
    for (let d = 0; d < 2; d++) {
        const pts  = idx.map(i => fit.points[i * fit.dims + d]);
        const dot  = pts.reduce((t, v, i) => t + v * FIXTURE.points[i][d], 0);
        const sign = dot >= 0 ? 1 : -1;      // SVD2 has arbitrary sign
        pts.forEach((v, i) => expect(sign * v).toBeCloseTo(FIXTURE.points[i][d], 9));
    }
    FIXTURE.variance.forEach((v, d) => expect(fit.model.variance[d]).toBeCloseTo(v, 9));
});
